USE [master]
GO
/****** Object:  Database [importesdb]    Script Date: 18/8/2023 16:30:12 ******/
CREATE DATABASE [importesdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'importesdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\importesdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'importesdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\importesdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [importesdb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [importesdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [importesdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [importesdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [importesdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [importesdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [importesdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [importesdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [importesdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [importesdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [importesdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [importesdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [importesdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [importesdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [importesdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [importesdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [importesdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [importesdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [importesdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [importesdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [importesdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [importesdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [importesdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [importesdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [importesdb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [importesdb] SET  MULTI_USER 
GO
ALTER DATABASE [importesdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [importesdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [importesdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [importesdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [importesdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [importesdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [importesdb] SET QUERY_STORE = OFF
GO
USE [importesdb]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 18/8/2023 16:30:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Persona] [int] NOT NULL,
	[Contraseña] [varchar](200) NOT NULL,
	[Estado] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cuentas]    Script Date: 18/8/2023 16:30:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuentas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cliente] [int] NOT NULL,
	[NumeroCuenta] [varchar](200) NOT NULL,
	[TipoCuenta] [varchar](20) NOT NULL,
	[Saldo] [decimal](18, 2) NOT NULL,
	[Estado] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movimientos]    Script Date: 18/8/2023 16:30:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movimientos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cuenta] [int] NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[TipoMovimiento] [varchar](20) NOT NULL,
	[Valor] [decimal](18, 2) NOT NULL,
	[Saldo] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Personas]    Script Date: 18/8/2023 16:30:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](200) NOT NULL,
	[Genero] [varchar](20) NOT NULL,
	[Edad] [int] NOT NULL,
	[Identificacion] [varchar](40) NOT NULL,
	[Direccion] [varchar](300) NOT NULL,
	[Telefono] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Clientes] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [dbo].[Cuentas] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [dbo].[Clientes]  WITH CHECK ADD FOREIGN KEY([Persona])
REFERENCES [dbo].[Personas] ([Id])
GO
ALTER TABLE [dbo].[Cuentas]  WITH CHECK ADD FOREIGN KEY([Cliente])
REFERENCES [dbo].[Clientes] ([Id])
GO
ALTER TABLE [dbo].[Movimientos]  WITH CHECK ADD FOREIGN KEY([Cuenta])
REFERENCES [dbo].[Cuentas] ([Id])
GO
USE [master]
GO
ALTER DATABASE [importesdb] SET  READ_WRITE 
GO
